(defproblem p10 satellite
  (
	(instrument instrument0)
	(instrument instrument1)
	(instrument instrument2)
	(satellite satellite0)
	(satellite satellite1)
	(satellite satellite2)
	(mode spectrograph2)
	(mode image0)
	(mode infrared3)
	(mode thermograph1)
	(direction star0)
	(direction star1)
	(direction star3)
	(direction planet9)
	(direction groundstation2)
	(direction planet5)
	(direction phenomenon10)
	(direction planet4)
	(direction star8)
	(direction phenomenon6)
	(direction star7)
	(supports instrument0 spectrograph2)
	(supports instrument0 image0)
	(calibration_target instrument0 star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star1)
	(supports instrument1 image0)
	(supports instrument1 spectrograph2)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 star1)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon6)
	(supports instrument2 thermograph1)
	(supports instrument2 infrared3)
	(calibration_target instrument2 star1)
	(on_board instrument2 satellite2)
	(power_avail satellite2)
	(pointing satellite2 star7)
  )

(:unordered
   (do_observation star3 thermograph1)
   (do_observation planet9 infrared3)
   (do_observation phenomenon10 spectrograph2)
)

)
