(defproblem p07 satellite
  (
	(instrument instrument0)
	(instrument instrument1)
	(instrument instrument2)
	(instrument instrument3)
	(satellite satellite0)
	(satellite satellite1)
	(mode thermograph1)
	(mode spectrograph0)
	(direction star1)
	(direction star0)
	(direction star5)
	(direction star6)
	(direction planet2)
	(direction star4)
	(direction planet3)
	(supports instrument0 thermograph1)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 star1)
	(supports instrument1 spectrograph0)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star6)
	(supports instrument2 thermograph1)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 star1)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 star0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star4)
  )

(:unordered
   (do_observation planet2 spectrograph0)
   (do_observation planet3 spectrograph0)
)

)
